export interface Tool {
  id: string;
  title: string;
  description: string;
  category: string;
  icon: string;
  href: string;
}

export const tools: Tool[] = [
  {
    id: "json-formatter",
    title: "JSON Formatter",
    description: "Format, validate, and minify JSON data with line numbers and error highlighting.",
    category: "Developer",
    icon: "🔧",
    href: "/tools/json-formatter",
  },
  {
    id: "base64",
    title: "Base64 Encode/Decode",
    description: "Encode text to Base64 or decode Base64 strings back to plain text.",
    category: "Developer",
    icon: "🔐",
    href: "/tools/base64",
  },
  {
    id: "uuid-generator",
    title: "UUID Generator",
    description: "Generate random UUID v4 identifiers instantly. Batch generate up to 100.",
    category: "Developer",
    icon: "🆔",
    href: "/tools/uuid-generator",
  },
  {
    id: "password-generator",
    title: "Password Generator",
    description: "Create strong, secure passwords with customizable length and character options.",
    category: "Security",
    icon: "🔑",
    href: "/tools/password-generator",
  },
  {
    id: "word-counter",
    title: "Word Counter",
    description: "Count words, characters, sentences, and paragraphs in real-time.",
    category: "Productivity",
    icon: "📝",
    href: "/tools/word-counter",
  },
  {
    id: "color-converter",
    title: "Color Converter",
    description: "Convert between HEX, RGB, and HSL color formats with live preview.",
    category: "Design",
    icon: "🎨",
    href: "/tools/color-converter",
  },
  {
    id: "lorem-ipsum",
    title: "Lorem Ipsum Generator",
    description: "Generate placeholder text for designs, mockups, and prototypes.",
    category: "Productivity",
    icon: "📄",
    href: "/tools/lorem-ipsum",
  },
  {
    id: "hash-generator",
    title: "Hash Generator",
    description: "Generate MD5, SHA-1, SHA-256, and SHA-512 hashes from any text input.",
    category: "Security",
    icon: "#️⃣",
    href: "/tools/hash-generator",
  },
  {
    id: "qr-code",
    title: "QR Code Generator",
    description: "Create QR codes from text or URLs and download as PNG.",
    category: "Utility",
    icon: "📱",
    href: "/tools/qr-code",
  },
  {
    id: "markdown-preview",
    title: "Markdown Preview",
    description: "Write Markdown and see a live preview side-by-side.",
    category: "Developer",
    icon: "✍️",
    href: "/tools/markdown-preview",
  },
  {
    id: "text-diff",
    title: "Text Diff",
    description: "Compare two pieces of text side by side and see what changed.",
    category: "Developer",
    icon: "🔀",
    href: "/tools/text-diff",
  },
  {
    id: "url-encoder",
    title: "URL Encoder/Decoder",
    description: "Encode text to URL-safe strings or decode URL-encoded text back to plain text.",
    category: "Developer",
    icon: "🌐",
    href: "/tools/url-encoder",
  },
  {
    id: "jwt-decoder",
    title: "JWT Decoder",
    description: "Decode JSON Web Tokens to view their header, payload, and signature.",
    category: "Developer",
    icon: "🎫",
    href: "/tools/jwt-decoder",
  },
  {
    id: "timestamp-converter",
    title: "Timestamp Converter",
    description: "Convert between Unix timestamps, ISO 8601, RFC 2822, and relative time formats.",
    category: "Developer",
    icon: "🕐",
    href: "/tools/timestamp-converter",
  },
  {
    id: "regex-tester",
    title: "Regex Tester",
    description: "Test regular expressions with live highlighting, match details, and common presets.",
    category: "Developer",
    icon: "🔍",
    href: "/tools/regex-tester",
  },
  {
    id: "text-case",
    title: "Text Case Converter",
    description: "Convert text between UPPERCASE, lowercase, camelCase, snake_case, and more.",
    category: "Productivity",
    icon: "🔤",
    href: "/tools/text-case",
  },
  {
    id: "csv-to-json",
    title: "CSV to JSON",
    description: "Convert CSV data to JSON arrays with configurable delimiters and header options.",
    category: "Data",
    icon: "📊",
    href: "/tools/csv-to-json",
  },
  {
    id: "html-preview",
    title: "HTML Preview",
    description: "Write HTML and see a live preview in real-time with a split-pane editor.",
    category: "Code",
    icon: "🖥️",
    href: "/tools/html-preview",
  },
  {
    id: "cron-builder",
    title: "Cron Expression Builder",
    description: "Build cron expressions visually with a point-and-click interface and human-readable descriptions.",
    category: "DevOps",
    icon: "⏰",
    href: "/tools/cron-builder",
  },
  {
    id: "markdown-to-html",
    title: "Markdown to HTML",
    description: "Convert Markdown to clean, ready-to-use HTML with live preview.",
    category: "Code",
    icon: "📋",
    href: "/tools/markdown-to-html",
  },
  {
    id: "json-to-csv",
    title: "JSON to CSV",
    description: "Convert JSON arrays of objects to CSV format with customizable delimiters.",
    category: "Data",
    icon: "📊",
    href: "/tools/json-to-csv",
  },
  {
    id: "html-to-markdown",
    title: "HTML to Markdown",
    description: "Convert HTML code to clean, readable Markdown syntax.",
    category: "Code",
    icon: "📝",
    href: "/tools/html-to-markdown",
  },
  {
    id: "yaml-to-json",
    title: "YAML to JSON",
    description: "Convert YAML data to JSON format. Supports nested objects, arrays, and all YAML types.",
    category: "Data",
    icon: "📋",
    href: "/tools/yaml-to-json",
  },
  {
    id: "json-to-yaml",
    title: "JSON to YAML",
    description: "Convert JSON to clean, readable YAML. Perfect for config files and manifests.",
    category: "Data",
    icon: "📋",
    href: "/tools/json-to-yaml",
  },
];